version: "3"
services:
  app:
    image: ghcr.io/ovorobeva/beertimetelegrambot:latest
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - resources:/resources/
volumes:
  resources: