name: Docker Image CI

on:
  push:
    tags:
      - '*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

      - uses: olegtarasov/get-tag@v2.1
        id: tagName

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags:
            - ghcr.io/ovorobeva/beertimetelegrambot/bot:latest
            - ghcr.io/ovorobeva/beertimetelegrambot/bot:${{ steps.tagName.outputs.tag }}

      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: cd BeerTimeTelegramBot && docker-compose pull && docker-compose up -d


